
spring:
  application:
    name: MongoDB-Example

  data:
    mongodb:
#      uri: mongodb://127.0.0.1:27017/?connectTimeoutMS=30000&minPoolSize=0&maxPoolSize=10&maxIdleTimeMS=90000
      uri: mongodb://127.0.0.1:27021,127.0.0.1:27022,127.0.0.1:27023/?connectTimeoutMS=30000&minPoolSize=0&maxPoolSize=10&maxIdleTimeMS=90000
      database: kimbs

#      org.springframework.data.mapping.model.CamelCaseAbbreviatingFieldNamingStrategy;
#      org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy;
#      org.springframework.data.mapping.model.CamelCaseSplittingFieldNamingStrategy;
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

org:
  kimbs:
    use-mongo-replica: true
